[features]
seeds = false
skip-lint = false

[programs.localnet]
### WARNING: Be sure to change these pubkeys to reflect your deployed keypairs
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
hello_token = "GDch61JmJpTo9npwenypnk3KdofmozK1hNaTdbYRkNPb"
governance  = "6CunRn1u11RPrJAexedhXKsuek3gFJcEdSjavfLTBZp1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dependencies/spl_token_metadata.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "./dependencies/wormhole.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb"
program = "./dependencies/token_bridge.so"

[[test.genesis]]
address = "BnPgcSAhLM362Haqhe83XEHhkDGZqyXQeJWnWNPKWZmi"
program = "./dependencies/spl_governance.so"

[[test.genesis]]
address = "7Zq76qnnZJ7ZvZYSwTSx2aucZGPk4xknyBmXCpjKoDEX"
program = "./dependencies/spl_token.so"

[[test.genesis]]
address = "6yQfvhZjCefqk68aL5AeiQ9i2BBojquS4XAD9xqYk5ye"
program = "./dependencies/spl_associated_token_account.so"
